//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JLPTWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_Alphabet
    {
        public int AlphabetId { get; set; }
        public string Romaji { get; set; }
        public string Hiragana { get; set; }
        public string HiraganaImg { get; set; }
        public string Katakana { get; set; }
        public string KatakanaImg { get; set; }
        public Nullable<int> GroupSort { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public Nullable<System.DateTime> DeleteTime { get; set; }
    
        public virtual A_User A_User { get; set; }
    }
}
