//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JLPTWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_Kanji
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public A_Kanji()
        {
            this.A_KanjiExam = new HashSet<A_KanjiExam>();
        }
    
        public int KanjiId { get; set; }
        public string KanjiContent { get; set; }
        public string KanjiMean { get; set; }
        public string KanjiMeanDetail { get; set; }
        public string KanjiOn { get; set; }
        public string KanjiKun { get; set; }
        public string KanjiImgUrl { get; set; }
        public Nullable<int> KanjiStrokes { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> ActiveFlag { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public Nullable<System.DateTime> DeleteTime { get; set; }
    
        public virtual A_User A_User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<A_KanjiExam> A_KanjiExam { get; set; }
    }
}
