//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JLPTWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_KanjiExam
    {
        public long KanjiExId { get; set; }
        public Nullable<int> KanjiId { get; set; }
        public string KanjiMean { get; set; }
        public string KanjiMeanDetail { get; set; }
        public string Higarana { get; set; }
        public string KanjiContent { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> ActiveFlag { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public Nullable<System.DateTime> DeleteTime { get; set; }
    
        public virtual A_Kanji A_Kanji { get; set; }
        public virtual A_User A_User { get; set; }
    }
}
