//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JLPTWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_Sen_Mean
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public A_Sen_Mean()
        {
            this.A_Like = new HashSet<A_Like>();
            this.A_TopicSentence = new HashSet<A_TopicSentence>();
            this.A_Voc_Sen = new HashSet<A_Voc_Sen>();
        }
    
        public long SenMeanId { get; set; }
        public Nullable<long> SentenceId { get; set; }
        public Nullable<long> MeanId { get; set; }
        public Nullable<int> Sort { get; set; }
        public Nullable<int> ApproveUserId { get; set; }
        public Nullable<int> ApproveFlag { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> ActiveFlag { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public Nullable<System.DateTime> DeleteTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<A_Like> A_Like { get; set; }
        public virtual A_Mean A_Mean { get; set; }
        public virtual A_Sentence A_Sentence { get; set; }
        public virtual A_User A_User { get; set; }
        public virtual A_User A_User1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<A_TopicSentence> A_TopicSentence { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<A_Voc_Sen> A_Voc_Sen { get; set; }
    }
}
