//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JLPTWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_Sentence
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public A_Sentence()
        {
            this.A_Sen_Mean = new HashSet<A_Sen_Mean>();
        }
    
        public long SentenceId { get; set; }
        public string Sentence { get; set; }
        public int UserId { get; set; }
        public int ApproveUserId { get; set; }
        public int ApproveFlag { get; set; }
        public int ActiveFlag { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public Nullable<System.DateTime> DeleteTime { get; set; }
        public string SenSearch { get; set; }
        public string SenFormat { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<A_Sen_Mean> A_Sen_Mean { get; set; }
        public virtual A_User A_User { get; set; }
        public virtual A_User A_User1 { get; set; }
        public virtual A_User A_User2 { get; set; }
    }
}
