//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JLPTWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_TopicVocDetail
    {
        public int TopicVocDetailId { get; set; }
        public Nullable<int> TopicVocId { get; set; }
        public Nullable<long> VocMeanId { get; set; }
        public Nullable<long> SenMeanId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> ActiveFlag { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public Nullable<System.DateTime> DeleteTime { get; set; }
    
        public virtual A_TopicVoc A_TopicVoc { get; set; }
        public virtual A_User A_User { get; set; }
        public virtual A_Voc_Sen A_Voc_Sen { get; set; }
    }
}
