//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JLPTWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_Voc_Sen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public A_Voc_Sen()
        {
            this.A_TopicVocDetail = new HashSet<A_TopicVocDetail>();
        }
    
        public long VocMeanId { get; set; }
        public long SenMeanId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> ActiveFlag { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public Nullable<System.DateTime> DeleteTime { get; set; }
    
        public virtual A_Sen_Mean A_Sen_Mean { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<A_TopicVocDetail> A_TopicVocDetail { get; set; }
        public virtual A_User A_User { get; set; }
        public virtual A_Voc_Mean A_Voc_Mean { get; set; }
    }
}
