//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JLPTWeb.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class JLPTDatabaseEntities : DbContext
    {
        public JLPTDatabaseEntities()
            : base("name=JLPTDatabaseEntities")
        {
            ((IObjectContextAdapter)this).ObjectContext.CommandTimeout = 360;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<A_Alphabet> A_Alphabet { get; set; }
        public virtual DbSet<A_Comp> A_Comp { get; set; }
        public virtual DbSet<A_Country> A_Country { get; set; }
        public virtual DbSet<A_Kanji> A_Kanji { get; set; }
        public virtual DbSet<A_KanjiExam> A_KanjiExam { get; set; }
        public virtual DbSet<A_Level> A_Level { get; set; }
        public virtual DbSet<A_Like> A_Like { get; set; }
        public virtual DbSet<A_Mean> A_Mean { get; set; }
        public virtual DbSet<A_Role> A_Role { get; set; }
        public virtual DbSet<A_Sen_Mean> A_Sen_Mean { get; set; }
        public virtual DbSet<A_Sentence> A_Sentence { get; set; }
        public virtual DbSet<A_Topic> A_Topic { get; set; }
        public virtual DbSet<A_TopicSentence> A_TopicSentence { get; set; }
        public virtual DbSet<A_TopicVoc> A_TopicVoc { get; set; }
        public virtual DbSet<A_TopicVocDetail> A_TopicVocDetail { get; set; }
        public virtual DbSet<A_User> A_User { get; set; }
        public virtual DbSet<A_Voc_Mean> A_Voc_Mean { get; set; }
        public virtual DbSet<A_Voc_Sen> A_Voc_Sen { get; set; }
        public virtual DbSet<A_Vocabulary> A_Vocabulary { get; set; }
        public virtual DbSet<B_News> B_News { get; set; }
        public virtual DbSet<M_Grammar> M_Grammar { get; set; }
        public virtual DbSet<M_GrammarJP> M_GrammarJP { get; set; }
        public virtual DbSet<M_GrammarN1> M_GrammarN1 { get; set; }
        public virtual DbSet<M_GrammarN2> M_GrammarN2 { get; set; }
        public virtual DbSet<M_GrammarN3> M_GrammarN3 { get; set; }
        public virtual DbSet<M_GrammarN4> M_GrammarN4 { get; set; }
        public virtual DbSet<M_GrammarN5> M_GrammarN5 { get; set; }
        public virtual DbSet<M_GroupByBook> M_GroupByBook { get; set; }
        public virtual DbSet<M_Level> M_Level { get; set; }
        public virtual DbSet<M_Setting> M_Setting { get; set; }
        public virtual DbSet<M_Compare> M_Compare { get; set; }
    }
}
