//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JLPTWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_GrammarJP
    {
        public int GrammarID { get; set; }
        public int SubID { get; set; }
        public string LevelID { get; set; }
        public string Struct { get; set; }
        public string Mean { get; set; }
        public string Full { get; set; }
        public string Yobi_1 { get; set; }
        public string Yobi_2 { get; set; }
        public string Yobi_3 { get; set; }
        public string Yobi_4 { get; set; }
        public string Yobi_5 { get; set; }
        public Nullable<System.DateTime> InsDate { get; set; }
        public Nullable<System.DateTime> UpdDate { get; set; }
    }
}
